name: Run All Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-go-tests:
    name: Run go test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v3
    - name: Run go test
      run: make test
